### ISSUE TITLE
Draining connection request headers hangs if reqConn.Read() streams exactly 64 bytes

### ISSUE THREAD

**Issue by rdbell** [kingsamchen/Eureka#1]
Hi @kingsamchen, thanks for your HTTP Proxy example code.

https://github.com/kingsamchen/Eureka/blob/17b281b6ed8d785b49fda3aad5ac40231aaad011/HTTPProxy/golang/connection.go#L138-L155

With this implementation of `drainConnectRequestHeaders` if the input stream is exactly 64 bytes (or any multiple of 64) the function will hang at line 142 on the second pass because no more data will come into `reqConn.Read(buf)`.

To prevent hanging you can switch to something like `bufio.NewReader(conn).ReadString('\n')` or do this:

```
if n < bufferSize || buf[bufferSize-1] == byte('\n') {
  log.Print("Drained https connect request header")
  break
}
```

**Comment by kingsamchen** [comment]
Yes, it is indeed a potential issue.
Thanks for pointing out and also the feasible fix.
